### ISSUE TITLE
UnboundLocalError Exception ; Variant class _validate field

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.schema#14]
Jason,

I am getting a UnboundLocalError: local variable 'e' referenced before assignment

 line 287, in _validate (field.py)
    self._reraise_validation_error(e, value)
UnboundLocalError: local variable 'e' referenced before assignment

It seems a 'tab' issue?

Thanks

Carlos

**Comment by jamadden** [comment]
Can you be more specific about how and on what platform you're receiving that error? 

Just guessing based on what you said, but that looks like it could be a difference between Python 2 and Python 3 ([there are binding differences](http://portingguide.readthedocs.io/en/latest/exceptions.html#caught-exception-scope) between Python 2 and Python 3 when it comes to exception scope that would tend to explain that).

However, it appears that all supported platforms (py2, 3.4, 3.5, and 3.6) [cover the line you reference](https://coveralls.io/builds/12286689/source?filename=src%2Fnti%2Fschema%2Ffield.py#L287), so that is a bit surprising and needs more info.

**Comment by papachoco** [comment]
Jason,

I am attaching the code I am tox/testing  (it comes from nti.coremetadata) the error occur in python 3.5/6  (test_schema.py line 53)

Thx
Carlos
[code.zip](https://github.com/NextThought/nti.schema/files/1354545/code.zip)

**Comment by jamadden** [comment]
OK, thanks, but there's not a clear error to see there, and that's a lot of code to try to dig through without a simple way to run it. Can you produce a failing example using just the code from this package (basically a [SSCCE](http://sscce.org))? Relying on a third-party closed-source package to produce an error doesn't help create a test case or otherwise identify the issue.

Even a complete traceback would be somewhat helpful (especially if it correlates to the code you were already able to provide). Assume I can't duplicate the results you're seeing because I don't have access to that third-party closed-source package.

**Comment by papachoco** [comment]
[test.zip](https://github.com/NextThought/nti.schema/files/1354571/test.zip)

Jason attaching one file that reproduces the error -py35/6 (the test layer loads nti.contentfragments). 

Let me know what else I can do 

Carlos

**Comment by papachoco** [comment]
[trace.txt](https://github.com/NextThought/nti.schema/files/1354575/trace.txt)
Trace attached

**Comment by jamadden** [comment]
Thanks.

For those wondering, the provided trace is 
```
Error in test test_model (nti.coremetadata.tests.test_schema.TestSchema)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "////.tox/py36/lib/python3.6/site-packages/nti/coremetadata/tests/test_schema.py", line 128, in test_model
    m.body = [b'aizen']
  File "////.tox/py36/lib/python3.6/site-packages/nti/coremetadata/tests/test_schema.py", line 79, in __set__
    super(AbstractFieldProperty, self).__set__(inst, value)
  File "////.tox/py36/lib/python3.6/site-packages/zope/schema/fieldproperty.py", line 77, in __set__
    field.validate(value)
  File "////.tox/py36/lib/python3.6/site-packages/zope/schema/_bootstrapfields.py", line 183, in validate
    self._validate(value)
  File "////.tox/py36/lib/python3.6/site-packages/nti/schema/field.py", line 164, in _validate
    super(FieldValidationMixin, self)._validate(value)
  File "////.tox/py36/lib/python3.6/site-packages/zope/schema/_field.py", line 525, in _validate
    errors = _validate_sequence(self.value_type, value)
  File "////.tox/py36/lib/python3.6/site-packages/zope/schema/_field.py", line 487, in _validate_sequence
    value_type.validate(item)
  File "////.tox/py36/lib/python3.6/site-packages/zope/schema/_bootstrapfields.py", line 183, in validate
    self._validate(value)
  File "////.tox/py36/lib/python3.6/site-packages/nti/schema/field.py", line 287, in _validate
    self._reraise_validation_error(e, value)
UnboundLocalError: local variable 'e' referenced before assignment
```

The provided code is also still way too complicated to post 😄 I'll see if I can reproduce with something more manageable.

**Comment by jamadden** [comment]
This code:
```python
from zope import interface

from zope.schema.fieldproperty import FieldProperty

from nti.schema.field import Text
from nti.schema.field import Variant

def test():
    class IModel(interface.Interface):
        body = Variant(
            fields=[
                Text(min_length=1,
                     description=u"Plain text that is sanitized and non-empty"),
            ],
            title=u"A body part",
            __name__='body')

    @interface.implementer(IModel)
    class Model(object):
        body = FieldProperty(IModel['body'])

    # body
    m = Model()
    m.body = b'abc'

test()
```

produces `UnboundLocalError` on Python 3.6:
```
Traceback (most recent call last):
  File "/test_schema.py", line 26, in <module>
    test()
  File "//test_schema.py", line 24, in test
    m.body = b'abc'
  File "//lib/python3.6/site-packages/zope/schema/fieldproperty.py", line 77, in __set__
    field.validate(value)
  File "//lib/python3.6/site-packages/zope/schema/_bootstrapfields.py", line 183, in validate
    self._validate(value)
  File "//lib/python3.6/site-packages/nti/schema/field.py", line 287, in _validate
    self._reraise_validation_error(e, value)
UnboundLocalError: local variable 'e' referenced before assignment
```

but fails with the (expected, correct) `WrongType` error on Python 2.7.

**Comment by jamadden** [comment]
The problem in the test suite is that it uses `nti.testing.matchers.not_validated_by`, which uses the `ValidatedBy` matcher. The `ValidatedBy` matcher does this (remember it's negated with a `not`):
```python
    def _matches( self, data ):
        try:
            self.field.validate( data )
        except Exception:
            return False
        else:
            return True
```
`UnboundLocalError` is an Exception, so the test passes.

The lint warning about "catching too general exception" might be right. We should add the ability for that matcher to specify the catch conditions.
