### ISSUE TITLE
Extensible UI Type tags

### ISSUE THREAD

**Issue by jzuech3** [NextThought/nti.schema#44]
It would be useful to be able to arbitrarily define new UI tags on fields and have them returned on the schema.

**Comment by jzuech3** [comment]
One example of this would be to define `groups` of fields that the UI would want to group. This group may be different by profile type.

**Comment by jamadden** [comment]
It makes sense that fields of the same type have the same schema items, while fields of different types can have different schema items, because schema items specify constraints on the values of a type of field. But different schema items for the same type---a heterogenous schema---make for complex branching trying to do something with the schema that you thought you understood.

I can get behind a *single* new schema value containing an arbitrary JSON data value, say `application_info`. It would be up to an application to agree on the meaning of that field and how it relates, if at all, to various field types.

**Comment by cutz** [comment]
> It makes sense that fields of the same type have the same schema items, while fields of different types can have different schema items, because schema items specify constraints on the values of a type of field. But different schema items for the same type---a heterogenous schema---make for complex branching trying to do something with the schema that you thought you understood.

I'm not sure I'm following this.

**Comment by jamadden** [comment]
The schema for a field is dominated by its `type` value: `int`, `string`, etc. All fields of a given type will have the same keys in the schema: min/max for int, min_length/max_length for string, and so on. (Just like the interface definitions for them over in zope.schema.)

Now imagine that sometimes an `int` schema has key 'foo', and sometimes 'bar', and sometimes both, and sometimes a 'string' schema has key 'foo' but never has 'bar' --- although that's not actually specified anywhere, it's just by observation. It's very difficult to make any sense of what to do with those extra (or missing) keys in a generic way.

That's why I don't think arbitrary keys belong at the top level.

**Comment by jzuech3** [comment]
Ah ok.  The arbitrary `application_info` dict would suit our purposes fine I think.

**Comment by jamadden** [comment]
> Just like the interface definitions for them over in zope.schema

Along those lines, we can and possibly should be spitting out much more information about the constraints on each field, guided by those interfaces.

> Ah ok. The arbitrary application_info dict would suit our purposes fine I think.

OK, if we can get #45 buttoned down, we can move on to these two issues (I suspect there might be conflicts to resolve doing them at the same time.)
